//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureMedMail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpFileValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpFileValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureMedMail.Resources.HelpFileValues", typeof(HelpFileValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1003.
        /// </summary>
        internal static string billDownloadToUploaderHelpTopicId {
            get {
                return ResourceManager.GetString("billDownloadToUploaderHelpTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string deleteAfterDownloadHelpTopicId {
            get {
                return ResourceManager.GetString("deleteAfterDownloadHelpTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1005.
        /// </summary>
        internal static string deleteAfterNumberOfDaysHelpTopicId {
            get {
                return ResourceManager.GetString("deleteAfterNumberOfDaysHelpTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1004.
        /// </summary>
        internal static string deleteAfterNumberOfDownloadsHelpTopicId {
            get {
                return ResourceManager.GetString("deleteAfterNumberOfDownloadsHelpTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1002.
        /// </summary>
        internal static string mustBeAccountMemberHelpTopicId {
            get {
                return ResourceManager.GetString("mustBeAccountMemberHelpTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001.
        /// </summary>
        internal static string mustBeAuthenticatedHelpTopicId {
            get {
                return ResourceManager.GetString("mustBeAuthenticatedHelpTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1006.
        /// </summary>
        internal static string notifyUploaderAfterDownloadHelpTopicId {
            get {
                return ResourceManager.GetString("notifyUploaderAfterDownloadHelpTopicId", resourceCulture);
            }
        }
    }
}
