//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureMedMail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UploadFileOptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadFileOptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureMedMail.Resources.UploadFileOptions", typeof(UploadFileOptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account of user who downloded the file.
        /// </summary>
        internal static string BILL_TO_DOWNLOADING_USER {
            get {
                return ResourceManager.GetString("BILL_TO_DOWNLOADING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string BILL_TO_MY_ACCOUNT {
            get {
                return ResourceManager.GetString("BILL_TO_MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a set number of days.
        /// </summary>
        internal static string DELETE_FILE_AFTER_NUMBER_OF_DAYS {
            get {
                return ResourceManager.GetString("DELETE_FILE_AFTER_NUMBER_OF_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a set number of downloads.
        /// </summary>
        internal static string DELETE_FILE_AFTER_NUMBER_OF_DOWNLOADS {
            get {
                return ResourceManager.GetString("DELETE_FILE_AFTER_NUMBER_OF_DOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately after it has been downloaded.
        /// </summary>
        internal static string DELETE_FILE_IMMEDIATELY {
            get {
                return ResourceManager.GetString("DELETE_FILE_IMMEDIATELY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous - Anyone with GUID/Password.
        /// </summary>
        internal static string DOWNLOAD_FOR_ANYONE {
            get {
                return ResourceManager.GetString("DOWNLOAD_FOR_ANYONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members of my account only.
        /// </summary>
        internal static string DOWNLOAD_FOR_MEMBERS_ONLY {
            get {
                return ResourceManager.GetString("DOWNLOAD_FOR_MEMBERS_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any registered SecureMedMail user.
        /// </summary>
        internal static string DOWNLOAD_FOR_REGISTERED_USERS {
            get {
                return ResourceManager.GetString("DOWNLOAD_FOR_REGISTERED_USERS", resourceCulture);
            }
        }
    }
}
